FROM mcr.microsoft.com/vscode/devcontainers/base:buster

RUN wget "https://releases.hashicorp.com/terraform/1.5.3/terraform_1.5.3_linux_amd64.zip" && \
        unzip terraform_1.5.3_linux_amd64.zip && \
        mv terraform /usr/local/bin/